export default [
  {
    id: "cGxhbmV0czox",
    name: "Tatooine",
    diameter: 10465,
    rotationPeriod: 23,
    orbitalPeriod: 304,
    gravity: "1 standard",
    population: 200000,
    climates: ["arid"],
    terrains: ["desert"],
    surfaceWater: 1
  },
  {
    id: "cGxhbmV0czoy",
    name: "Alderaan",
    diameter: 12500,
    rotationPeriod: 24,
    orbitalPeriod: 364,
    gravity: "1 standard",
    population: 2000000000,
    climates: ["temperate"],
    terrains: ["grasslands", "mountains"],
    surfaceWater: 40
  },
  {
    id: "cGxhbmV0czoz",
    name: "Yavin IV",
    diameter: 10200,
    rotationPeriod: 24,
    orbitalPeriod: 4818,
    gravity: "1 standard",
    population: 1000,
    climates: ["temperate", "tropical"],
    terrains: ["jungle", "rainforests"],
    surfaceWater: 8
  },
  {
    id: "cGxhbmV0czo0",
    name: "Hoth",
    diameter: 7200,
    rotationPeriod: 23,
    orbitalPeriod: 549,
    gravity: "1.1 standard",
    population: null,
    climates: ["frozen"],
    terrains: ["tundra", "ice caves", "mountain ranges"],
    surfaceWater: 100
  },
  {
    id: "cGxhbmV0czo1",
    name: "Dagobah",
    diameter: 8900,
    rotationPeriod: 23,
    orbitalPeriod: 341,
    gravity: "N/A",
    population: null,
    climates: ["murky"],
    terrains: ["swamp", "jungles"],
    surfaceWater: 8
  },
  {
    id: "cGxhbmV0czo2",
    name: "Bespin",
    diameter: 118000,
    rotationPeriod: 12,
    orbitalPeriod: 5110,
    gravity: "1.5 (surface), 1 standard (Cloud City)",
    population: 6000000,
    climates: ["temperate"],
    terrains: ["gas giant"],
    surfaceWater: 0
  },
  {
    id: "cGxhbmV0czo3",
    name: "Endor",
    diameter: 4900,
    rotationPeriod: 18,
    orbitalPeriod: 402,
    gravity: "0.85 standard",
    population: 30000000,
    climates: ["temperate"],
    terrains: ["forests", "mountains", "lakes"],
    surfaceWater: 8
  },
  {
    id: "cGxhbmV0czo4",
    name: "Naboo",
    diameter: 12120,
    rotationPeriod: 26,
    orbitalPeriod: 312,
    gravity: "1 standard",
    population: null,
    climates: ["temperate"],
    terrains: ["grassy hills", "swamps", "forests", "mountains"],
    surfaceWater: 12
  },
  {
    id: "cGxhbmV0czo5",
    name: "Coruscant",
    diameter: 12240,
    rotationPeriod: 24,
    orbitalPeriod: 368,
    gravity: "1 standard",
    population: null,
    climates: ["temperate"],
    terrains: ["cityscape", "mountains"],
    surfaceWater: null
  },
  {
    id: "cGxhbmV0czoxMA==",
    name: "Kamino",
    diameter: 19720,
    rotationPeriod: 27,
    orbitalPeriod: 463,
    gravity: "1 standard",
    population: 1000000000,
    climates: ["temperate"],
    terrains: ["ocean"],
    surfaceWater: 100
  },
  {
    id: "cGxhbmV0czoxMQ==",
    name: "Geonosis",
    diameter: 11370,
    rotationPeriod: 30,
    orbitalPeriod: 256,
    gravity: "0.9 standard",
    population: null,
    climates: ["temperate", "arid"],
    terrains: ["rock", "desert", "mountain", "barren"],
    surfaceWater: 5
  },
  {
    id: "cGxhbmV0czoxMg==",
    name: "Utapau",
    diameter: 12900,
    rotationPeriod: 27,
    orbitalPeriod: 351,
    gravity: "1 standard",
    population: 95000000,
    climates: ["temperate", "arid", "windy"],
    terrains: ["scrublands", "savanna", "canyons", "sinkholes"],
    surfaceWater: 0.9
  },
  {
    id: "cGxhbmV0czoxMw==",
    name: "Mustafar",
    diameter: 4200,
    rotationPeriod: 36,
    orbitalPeriod: 412,
    gravity: "1 standard",
    population: 20000,
    climates: ["hot"],
    terrains: ["volcanoes", "lava rivers", "mountains", "caves"],
    surfaceWater: 0
  },
  {
    id: "cGxhbmV0czoxNA==",
    name: "Kashyyyk",
    diameter: 12765,
    rotationPeriod: 26,
    orbitalPeriod: 381,
    gravity: "1 standard",
    population: 45000000,
    climates: ["tropical"],
    terrains: ["jungle", "forests", "lakes", "rivers"],
    surfaceWater: 60
  },
  {
    id: "cGxhbmV0czoxNQ==",
    name: "Polis Massa",
    diameter: 0,
    rotationPeriod: 24,
    orbitalPeriod: 590,
    gravity: "0.56 standard",
    population: 1000000,
    climates: ["artificial temperate"],
    terrains: ["airless asteroid"],
    surfaceWater: 0
  },
  {
    id: "cGxhbmV0czoxNg==",
    name: "Mygeeto",
    diameter: 10088,
    rotationPeriod: 12,
    orbitalPeriod: 167,
    gravity: "1 standard",
    population: 19000000,
    climates: ["frigid"],
    terrains: ["glaciers", "mountains", "ice canyons"],
    surfaceWater: null
  },
  {
    id: "cGxhbmV0czoxNw==",
    name: "Felucia",
    diameter: 9100,
    rotationPeriod: 34,
    orbitalPeriod: 231,
    gravity: "0.75 standard",
    population: 8500000,
    climates: ["hot", "humid"],
    terrains: ["fungus forests"],
    surfaceWater: null
  },
  {
    id: "cGxhbmV0czoxOA==",
    name: "Cato Neimoidia",
    diameter: 0,
    rotationPeriod: 25,
    orbitalPeriod: 278,
    gravity: "1 standard",
    population: 10000000,
    climates: ["temperate", "moist"],
    terrains: ["mountains", "fields", "forests", "rock arches"],
    surfaceWater: null
  },
  {
    id: "cGxhbmV0czoxOQ==",
    name: "Saleucami",
    diameter: 14920,
    rotationPeriod: 26,
    orbitalPeriod: 392,
    gravity: "unknown",
    population: 1400000000,
    climates: ["hot"],
    terrains: ["caves", "desert", "mountains", "volcanoes"],
    surfaceWater: null
  },
  {
    id: "cGxhbmV0czoyMA==",
    name: "Stewjon",
    diameter: 0,
    rotationPeriod: null,
    orbitalPeriod: null,
    gravity: "1 standard",
    population: null,
    climates: ["temperate"],
    terrains: ["grass"],
    surfaceWater: null
  },
  {
    id: "cGxhbmV0czoyMQ==",
    name: "Eriadu",
    diameter: 13490,
    rotationPeriod: 24,
    orbitalPeriod: 360,
    gravity: "1 standard",
    population: null,
    climates: ["polluted"],
    terrains: ["cityscape"],
    surfaceWater: null
  },
  {
    id: "cGxhbmV0czoyMg==",
    name: "Corellia",
    diameter: 11000,
    rotationPeriod: 25,
    orbitalPeriod: 329,
    gravity: "1 standard",
    population: null,
    climates: ["temperate"],
    terrains: ["plains", "urban", "hills", "forests"],
    surfaceWater: 70
  },
  {
    id: "cGxhbmV0czoyMw==",
    name: "Rodia",
    diameter: 7549,
    rotationPeriod: 29,
    orbitalPeriod: 305,
    gravity: "1 standard",
    population: 1300000000,
    climates: ["hot"],
    terrains: ["jungles", "oceans", "urban", "swamps"],
    surfaceWater: 60
  },
  {
    id: "cGxhbmV0czoyNA==",
    name: "Nal Hutta",
    diameter: 12150,
    rotationPeriod: 87,
    orbitalPeriod: 413,
    gravity: "1 standard",
    population: null,
    climates: ["temperate"],
    terrains: ["urban", "oceans", "swamps", "bogs"],
    surfaceWater: null
  },
  {
    id: "cGxhbmV0czoyNQ==",
    name: "Dantooine",
    diameter: 9830,
    rotationPeriod: 25,
    orbitalPeriod: 378,
    gravity: "1 standard",
    population: 1000,
    climates: ["temperate"],
    terrains: ["oceans", "savannas", "mountains", "grasslands"],
    surfaceWater: null
  },
  {
    id: "cGxhbmV0czoyNg==",
    name: "Bestine IV",
    diameter: 6400,
    rotationPeriod: 26,
    orbitalPeriod: 680,
    gravity: "unknown",
    population: 62000000,
    climates: ["temperate"],
    terrains: ["rocky islands", "oceans"],
    surfaceWater: 98
  },
  {
    id: "cGxhbmV0czoyNw==",
    name: "Ord Mantell",
    diameter: 14050,
    rotationPeriod: 26,
    orbitalPeriod: 334,
    gravity: "1 standard",
    population: null,
    climates: ["temperate"],
    terrains: ["plains", "seas", "mesas"],
    surfaceWater: 10
  },
  {
    id: "cGxhbmV0czoyOA==",
    name: "unknown",
    diameter: 0,
    rotationPeriod: 0,
    orbitalPeriod: 0,
    gravity: "unknown",
    population: null,
    climates: ["unknown"],
    terrains: ["unknown"],
    surfaceWater: null
  },
  {
    id: "cGxhbmV0czoyOQ==",
    name: "Trandosha",
    diameter: 0,
    rotationPeriod: 25,
    orbitalPeriod: 371,
    gravity: "0.62 standard",
    population: 42000000,
    climates: ["arid"],
    terrains: ["mountains", "seas", "grasslands", "deserts"],
    surfaceWater: null
  },
  {
    id: "cGxhbmV0czozMA==",
    name: "Socorro",
    diameter: 0,
    rotationPeriod: 20,
    orbitalPeriod: 326,
    gravity: "1 standard",
    population: 300000000,
    climates: ["arid"],
    terrains: ["deserts", "mountains"],
    surfaceWater: null
  },
  {
    id: "cGxhbmV0czozMQ==",
    name: "Mon Cala",
    diameter: 11030,
    rotationPeriod: 21,
    orbitalPeriod: 398,
    gravity: "1",
    population: null,
    climates: ["temperate"],
    terrains: ["oceans", "reefs", "islands"],
    surfaceWater: 100
  },
  {
    id: "cGxhbmV0czozMg==",
    name: "Chandrila",
    diameter: 13500,
    rotationPeriod: 20,
    orbitalPeriod: 368,
    gravity: "1",
    population: 1200000000,
    climates: ["temperate"],
    terrains: ["plains", "forests"],
    surfaceWater: 40
  },
  {
    id: "cGxhbmV0czozMw==",
    name: "Sullust",
    diameter: 12780,
    rotationPeriod: 20,
    orbitalPeriod: 263,
    gravity: "1",
    population: null,
    climates: ["superheated"],
    terrains: ["mountains", "volcanoes", "rocky deserts"],
    surfaceWater: 5
  },
  {
    id: "cGxhbmV0czozNA==",
    name: "Toydaria",
    diameter: 7900,
    rotationPeriod: 21,
    orbitalPeriod: 184,
    gravity: "1",
    population: 11000000,
    climates: ["temperate"],
    terrains: ["swamps", "lakes"],
    surfaceWater: null
  },
  {
    id: "cGxhbmV0czozNQ==",
    name: "Malastare",
    diameter: 18880,
    rotationPeriod: 26,
    orbitalPeriod: 201,
    gravity: "1.56",
    population: 2000000000,
    climates: ["arid", "temperate", "tropical"],
    terrains: ["swamps", "deserts", "jungles", "mountains"],
    surfaceWater: null
  },
  {
    id: "cGxhbmV0czozNg==",
    name: "Dathomir",
    diameter: 10480,
    rotationPeriod: 24,
    orbitalPeriod: 491,
    gravity: "0.9",
    population: 5200,
    climates: ["temperate"],
    terrains: ["forests", "deserts", "savannas"],
    surfaceWater: null
  },
  {
    id: "cGxhbmV0czozNw==",
    name: "Ryloth",
    diameter: 10600,
    rotationPeriod: 30,
    orbitalPeriod: 305,
    gravity: "1",
    population: 1500000000,
    climates: ["temperate", "arid", "subartic"],
    terrains: ["mountains", "valleys", "deserts", "tundra"],
    surfaceWater: 5
  },
  {
    id: "cGxhbmV0czozOA==",
    name: "Aleen Minor",
    diameter: null,
    rotationPeriod: null,
    orbitalPeriod: null,
    gravity: "unknown",
    population: null,
    climates: ["unknown"],
    terrains: ["unknown"],
    surfaceWater: null
  },
  {
    id: "cGxhbmV0czozOQ==",
    name: "Vulpter",
    diameter: 14900,
    rotationPeriod: 22,
    orbitalPeriod: 391,
    gravity: "1",
    population: 421000000,
    climates: ["temperate", "artic"],
    terrains: ["urban", "barren"],
    surfaceWater: null
  },
  {
    id: "cGxhbmV0czo0MA==",
    name: "Troiken",
    diameter: null,
    rotationPeriod: null,
    orbitalPeriod: null,
    gravity: "unknown",
    population: null,
    climates: ["unknown"],
    terrains: ["desert", "tundra", "rainforests", "mountains"],
    surfaceWater: null
  },
  {
    id: "cGxhbmV0czo0MQ==",
    name: "Tund",
    diameter: 12190,
    rotationPeriod: 48,
    orbitalPeriod: 1770,
    gravity: "unknown",
    population: 0,
    climates: ["unknown"],
    terrains: ["barren", "ash"],
    surfaceWater: null
  },
  {
    id: "cGxhbmV0czo0Mg==",
    name: "Haruun Kal",
    diameter: 10120,
    rotationPeriod: 25,
    orbitalPeriod: 383,
    gravity: "0.98",
    population: 705300,
    climates: ["temperate"],
    terrains: ["toxic cloudsea", "plateaus", "volcanoes"],
    surfaceWater: null
  },
  {
    id: "cGxhbmV0czo0Mw==",
    name: "Cerea",
    diameter: null,
    rotationPeriod: 27,
    orbitalPeriod: 386,
    gravity: "1",
    population: 450000000,
    climates: ["temperate"],
    terrains: ["verdant"],
    surfaceWater: 20
  },
  {
    id: "cGxhbmV0czo0NA==",
    name: "Glee Anselm",
    diameter: 15600,
    rotationPeriod: 33,
    orbitalPeriod: 206,
    gravity: "1",
    population: 500000000,
    climates: ["tropical", "temperate"],
    terrains: ["lakes", "islands", "swamps", "seas"],
    surfaceWater: 80
  },
  {
    id: "cGxhbmV0czo0NQ==",
    name: "Iridonia",
    diameter: null,
    rotationPeriod: 29,
    orbitalPeriod: 413,
    gravity: "unknown",
    population: null,
    climates: ["unknown"],
    terrains: ["rocky canyons", "acid pools"],
    surfaceWater: null
  },
  {
    id: "cGxhbmV0czo0Ng==",
    name: "Tholoth",
    diameter: null,
    rotationPeriod: null,
    orbitalPeriod: null,
    gravity: "unknown",
    population: null,
    climates: ["unknown"],
    terrains: ["unknown"],
    surfaceWater: null
  },
  {
    id: "cGxhbmV0czo0Nw==",
    name: "Iktotch",
    diameter: null,
    rotationPeriod: 22,
    orbitalPeriod: 481,
    gravity: "1",
    population: null,
    climates: ["arid", "rocky", "windy"],
    terrains: ["rocky"],
    surfaceWater: null
  },
  {
    id: "cGxhbmV0czo0OA==",
    name: "Quermia",
    diameter: null,
    rotationPeriod: null,
    orbitalPeriod: null,
    gravity: "unknown",
    population: null,
    climates: ["unknown"],
    terrains: ["unknown"],
    surfaceWater: null
  },
  {
    id: "cGxhbmV0czo0OQ==",
    name: "Dorin",
    diameter: 13400,
    rotationPeriod: 22,
    orbitalPeriod: 409,
    gravity: "1",
    population: null,
    climates: ["temperate"],
    terrains: ["unknown"],
    surfaceWater: null
  },
  {
    id: "cGxhbmV0czo1MA==",
    name: "Champala",
    diameter: null,
    rotationPeriod: 27,
    orbitalPeriod: 318,
    gravity: "1",
    population: null,
    climates: ["temperate"],
    terrains: ["oceans", "rainforests", "plateaus"],
    surfaceWater: null
  },
  {
    id: "cGxhbmV0czo1MQ==",
    name: "Mirial",
    diameter: null,
    rotationPeriod: null,
    orbitalPeriod: null,
    gravity: "unknown",
    population: null,
    climates: ["unknown"],
    terrains: ["deserts"],
    surfaceWater: null
  },
  {
    id: "cGxhbmV0czo1Mg==",
    name: "Serenno",
    diameter: null,
    rotationPeriod: null,
    orbitalPeriod: null,
    gravity: "unknown",
    population: null,
    climates: ["unknown"],
    terrains: ["rainforests", "rivers", "mountains"],
    surfaceWater: null
  },
  {
    id: "cGxhbmV0czo1Mw==",
    name: "Concord Dawn",
    diameter: null,
    rotationPeriod: null,
    orbitalPeriod: null,
    gravity: "unknown",
    population: null,
    climates: ["unknown"],
    terrains: ["jungles", "forests", "deserts"],
    surfaceWater: null
  },
  {
    id: "cGxhbmV0czo1NA==",
    name: "Zolan",
    diameter: null,
    rotationPeriod: null,
    orbitalPeriod: null,
    gravity: "unknown",
    population: null,
    climates: ["unknown"],
    terrains: ["unknown"],
    surfaceWater: null
  },
  {
    id: "cGxhbmV0czo1NQ==",
    name: "Ojom",
    diameter: null,
    rotationPeriod: null,
    orbitalPeriod: null,
    gravity: "unknown",
    population: 500000000,
    climates: ["frigid"],
    terrains: ["oceans", "glaciers"],
    surfaceWater: 100
  },
  {
    id: "cGxhbmV0czo1Ng==",
    name: "Skako",
    diameter: null,
    rotationPeriod: 27,
    orbitalPeriod: 384,
    gravity: "1",
    population: null,
    climates: ["temperate"],
    terrains: ["urban", "vines"],
    surfaceWater: null
  },
  {
    id: "cGxhbmV0czo1Nw==",
    name: "Muunilinst",
    diameter: 13800,
    rotationPeriod: 28,
    orbitalPeriod: 412,
    gravity: "1",
    population: null,
    climates: ["temperate"],
    terrains: ["plains", "forests", "hills", "mountains"],
    surfaceWater: 25
  },
  {
    id: "cGxhbmV0czo1OA==",
    name: "Shili",
    diameter: null,
    rotationPeriod: null,
    orbitalPeriod: null,
    gravity: "1",
    population: null,
    climates: ["temperate"],
    terrains: ["cities", "savannahs", "seas", "plains"],
    surfaceWater: null
  },
  {
    id: "cGxhbmV0czo1OQ==",
    name: "Kalee",
    diameter: 13850,
    rotationPeriod: 23,
    orbitalPeriod: 378,
    gravity: "1",
    population: null,
    climates: ["arid", "temperate", "tropical"],
    terrains: ["rainforests", "cliffs", "canyons", "seas"],
    surfaceWater: null
  },
  {
    id: "cGxhbmV0czo2MA==",
    name: "Umbara",
    diameter: null,
    rotationPeriod: null,
    orbitalPeriod: null,
    gravity: "unknown",
    population: null,
    climates: ["unknown"],
    terrains: ["unknown"],
    surfaceWater: null
  }
];
