export default [
  {
    name: "Sand Crawler",
    model: "Digger Crawler",
    manufacturer: "Corellia Mining Corporation",
    cost_in_credits: "150000",
    length: "36.8",
    max_atmosphering_speed: "30",
    crew: "46",
    passengers: "30",
    cargo_capacity: "50000",
    consumables: "2 months",
    vehicle_class: "wheeled",
    pilots: [],
    films: ["5", "1"],
    id: "4"
  },
  {
    name: "T-16 skyhopper",
    model: "T-16 skyhopper",
    manufacturer: "Incom Corporation",
    cost_in_credits: "14500",
    length: "10.4",
    max_atmosphering_speed: "1200",
    crew: "1",
    passengers: "1",
    cargo_capacity: "50",
    consumables: "0",
    vehicle_class: "repulsorcraft",
    pilots: [],
    films: ["1"],
    id: "6"
  },
  {
    name: "X-34 landspeeder",
    model: "X-34 landspeeder",
    manufacturer: "SoroSuub Corporation",
    cost_in_credits: "10550",
    length: "3.4",
    max_atmosphering_speed: "250",
    crew: "1",
    passengers: "1",
    cargo_capacity: "5",
    consumables: "unknown",
    vehicle_class: "repulsorcraft",
    pilots: [],
    films: ["1"],
    id: "7"
  },
  {
    name: "TIE/LN starfighter",
    model: "Twin Ion Engine/Ln Starfighter",
    manufacturer: "Sienar Fleet Systems",
    cost_in_credits: "unknown",
    length: "6.4",
    max_atmosphering_speed: "1200",
    crew: "1",
    passengers: "0",
    cargo_capacity: "65",
    consumables: "2 days",
    vehicle_class: "starfighter",
    pilots: [],
    films: ["2", "3", "1"],
    id: "8"
  },
  {
    name: "Snowspeeder",
    model: "t-47 airspeeder",
    manufacturer: "Incom corporation",
    cost_in_credits: "unknown",
    length: "4.5",
    max_atmosphering_speed: "650",
    crew: "2",
    passengers: "0",
    cargo_capacity: "10",
    consumables: "none",
    vehicle_class: "airspeeder",
    pilots: ["1", "18"],
    films: ["2"],
    id: "14"
  },
  {
    name: "TIE bomber",
    model: "TIE/sa bomber",
    manufacturer: "Sienar Fleet Systems",
    cost_in_credits: "unknown",
    length: "7.8",
    max_atmosphering_speed: "850",
    crew: "1",
    passengers: "0",
    cargo_capacity: "none",
    consumables: "2 days",
    vehicle_class: "space/planetary bomber",
    pilots: [],
    films: ["2", "3"],
    id: "16"
  },
  {
    name: "AT-AT",
    model: "All Terrain Armored Transport",
    manufacturer: "Kuat Drive Yards, Imperial Department of Military Research",
    cost_in_credits: "unknown",
    length: "20",
    max_atmosphering_speed: "60",
    crew: "5",
    passengers: "40",
    cargo_capacity: "1000",
    consumables: "unknown",
    vehicle_class: "assault walker",
    pilots: [],
    films: ["2", "3"],
    id: "18"
  },
  {
    name: "AT-ST",
    model: "All Terrain Scout Transport",
    manufacturer: "Kuat Drive Yards, Imperial Department of Military Research",
    cost_in_credits: "unknown",
    length: "2",
    max_atmosphering_speed: "90",
    crew: "2",
    passengers: "0",
    cargo_capacity: "200",
    consumables: "none",
    vehicle_class: "walker",
    pilots: ["13"],
    films: ["2", "3"],
    id: "19"
  },
  {
    name: "Storm IV Twin-Pod cloud car",
    model: "Storm IV Twin-Pod",
    manufacturer: "Bespin Motors",
    cost_in_credits: "75000",
    length: "7",
    max_atmosphering_speed: "1500",
    crew: "2",
    passengers: "0",
    cargo_capacity: "10",
    consumables: "1 day",
    vehicle_class: "repulsorcraft",
    pilots: [],
    films: ["2"],
    id: "20"
  },
  {
    name: "Sail barge",
    model: "Modified Luxury Sail Barge",
    manufacturer: "Ubrikkian Industries Custom Vehicle Division",
    cost_in_credits: "285000",
    length: "30",
    max_atmosphering_speed: "100",
    crew: "26",
    passengers: "500",
    cargo_capacity: "2000000",
    consumables: "Live food tanks",
    vehicle_class: "sail barge",
    pilots: [],
    films: ["3"],
    id: "24"
  },
  {
    name: "Bantha-II cargo skiff",
    model: "Bantha-II",
    manufacturer: "Ubrikkian Industries",
    cost_in_credits: "8000",
    length: "9.5",
    max_atmosphering_speed: "250",
    crew: "5",
    passengers: "16",
    cargo_capacity: "135000",
    consumables: "1 day",
    vehicle_class: "repulsorcraft cargo skiff",
    pilots: [],
    films: ["3"],
    id: "25"
  },
  {
    name: "TIE/IN interceptor",
    model: "Twin Ion Engine Interceptor",
    manufacturer: "Sienar Fleet Systems",
    cost_in_credits: "unknown",
    length: "9.6",
    max_atmosphering_speed: "1250",
    crew: "1",
    passengers: "0",
    cargo_capacity: "75",
    consumables: "2 days",
    vehicle_class: "starfighter",
    pilots: [],
    films: ["3"],
    id: "26"
  },
  {
    name: "Imperial Speeder Bike",
    model: "74-Z speeder bike",
    manufacturer: "Aratech Repulsor Company",
    cost_in_credits: "8000",
    length: "3",
    max_atmosphering_speed: "360",
    crew: "1",
    passengers: "1",
    cargo_capacity: "4",
    consumables: "1 day",
    vehicle_class: "speeder",
    pilots: ["1", "5"],
    films: ["3"],
    id: "30"
  },
  {
    name: "Vulture Droid",
    model: "Vulture-class droid starfighter",
    manufacturer: "Haor Chall Engineering, Baktoid Armor Workshop",
    cost_in_credits: "unknown",
    length: "3.5",
    max_atmosphering_speed: "1200",
    crew: "0",
    passengers: "0",
    cargo_capacity: "0",
    consumables: "none",
    vehicle_class: "starfighter",
    pilots: [],
    films: ["4", "6"],
    id: "33"
  },
  {
    name: "Multi-Troop Transport",
    model: "Multi-Troop Transport",
    manufacturer: "Baktoid Armor Workshop",
    cost_in_credits: "138000",
    length: "31",
    max_atmosphering_speed: "35",
    crew: "4",
    passengers: "112",
    cargo_capacity: "12000",
    consumables: "unknown",
    vehicle_class: "repulsorcraft",
    pilots: [],
    films: ["4"],
    id: "34"
  },
  {
    name: "Armored Assault Tank",
    model: "Armoured Assault Tank",
    manufacturer: "Baktoid Armor Workshop",
    cost_in_credits: "unknown",
    length: "9.75",
    max_atmosphering_speed: "55",
    crew: "4",
    passengers: "6",
    cargo_capacity: "unknown",
    consumables: "unknown",
    vehicle_class: "repulsorcraft",
    pilots: [],
    films: ["4"],
    id: "35"
  },
  {
    name: "Single Trooper Aerial Platform",
    model: "Single Trooper Aerial Platform",
    manufacturer: "Baktoid Armor Workshop",
    cost_in_credits: "2500",
    length: "2",
    max_atmosphering_speed: "400",
    crew: "1",
    passengers: "0",
    cargo_capacity: "none",
    consumables: "none",
    vehicle_class: "repulsorcraft",
    pilots: [],
    films: ["4"],
    id: "36"
  },
  {
    name: "C-9979 landing craft",
    model: "C-9979 landing craft",
    manufacturer: "Haor Chall Engineering",
    cost_in_credits: "200000",
    length: "210",
    max_atmosphering_speed: "587",
    crew: "140",
    passengers: "284",
    cargo_capacity: "1800000",
    consumables: "1 day",
    vehicle_class: "landing craft",
    pilots: [],
    films: ["4"],
    id: "37"
  },
  {
    name: "Tribubble bongo",
    model: "Tribubble bongo",
    manufacturer: "Otoh Gunga Bongameken Cooperative",
    cost_in_credits: "unknown",
    length: "15",
    max_atmosphering_speed: "85",
    crew: "1",
    passengers: "2",
    cargo_capacity: "1600",
    consumables: "unknown",
    vehicle_class: "submarine",
    pilots: ["10", "32"],
    films: ["4"],
    id: "38"
  },
  {
    name: "Sith speeder",
    model: "FC-20 speeder bike",
    manufacturer: "Razalon",
    cost_in_credits: "4000",
    length: "1.5",
    max_atmosphering_speed: "180",
    crew: "1",
    passengers: "0",
    cargo_capacity: "2",
    consumables: "unknown",
    vehicle_class: "speeder",
    pilots: ["44"],
    films: ["4"],
    id: "42"
  },
  {
    name: "Zephyr-G swoop bike",
    model: "Zephyr-G swoop bike",
    manufacturer: "Mobquet Swoops and Speeders",
    cost_in_credits: "5750",
    length: "3.68",
    max_atmosphering_speed: "350",
    crew: "1",
    passengers: "1",
    cargo_capacity: "200",
    consumables: "none",
    vehicle_class: "repulsorcraft",
    pilots: ["11"],
    films: ["5"],
    id: "44"
  },
  {
    name: "Koro-2 Exodrive airspeeder",
    model: "Koro-2 Exodrive airspeeder",
    manufacturer: "Desler Gizh Outworld Mobility Corporation",
    cost_in_credits: "unknown",
    length: "6.6",
    max_atmosphering_speed: "800",
    crew: "1",
    passengers: "1",
    cargo_capacity: "80",
    consumables: "unknown",
    vehicle_class: "airspeeder",
    pilots: ["70"],
    films: ["5"],
    id: "45"
  },
  {
    name: "XJ-6 airspeeder",
    model: "XJ-6 airspeeder",
    manufacturer: "Narglatch AirTech prefabricated kit",
    cost_in_credits: "unknown",
    length: "6.23",
    max_atmosphering_speed: "720",
    crew: "1",
    passengers: "1",
    cargo_capacity: "unknown",
    consumables: "unknown",
    vehicle_class: "airspeeder",
    pilots: ["11"],
    films: ["5"],
    id: "46"
  },
  {
    name: "LAAT/i",
    model: "Low Altitude Assault Transport/infrantry",
    manufacturer: "Rothana Heavy Engineering",
    cost_in_credits: "unknown",
    length: "17.4",
    max_atmosphering_speed: "620",
    crew: "6",
    passengers: "30",
    cargo_capacity: "170",
    consumables: "unknown",
    vehicle_class: "gunship",
    pilots: [],
    films: ["5", "6"],
    id: "50"
  },
  {
    name: "LAAT/c",
    model: "Low Altitude Assault Transport/carrier",
    manufacturer: "Rothana Heavy Engineering",
    cost_in_credits: "unknown",
    length: "28.82",
    max_atmosphering_speed: "620",
    crew: "1",
    passengers: "0",
    cargo_capacity: "40000",
    consumables: "unknown",
    vehicle_class: "gunship",
    pilots: [],
    films: ["5"],
    id: "51"
  },
  {
    name: "Tsmeu-6 personal wheel bike",
    model: "Tsmeu-6 personal wheel bike",
    manufacturer: "Z-Gomot Ternbuell Guppat Corporation",
    cost_in_credits: "15000",
    length: "3.5",
    max_atmosphering_speed: "330",
    crew: "1",
    passengers: "1",
    cargo_capacity: "10",
    consumables: "none",
    vehicle_class: "wheeled walker",
    pilots: ["79"],
    films: ["6"],
    id: "60"
  },
  {
    name: "Emergency Firespeeder",
    model: "Fire suppression speeder",
    manufacturer: "unknown",
    cost_in_credits: "unknown",
    length: "unknown",
    max_atmosphering_speed: "unknown",
    crew: "2",
    passengers: "unknown",
    cargo_capacity: "unknown",
    consumables: "unknown",
    vehicle_class: "fire suppression ship",
    pilots: [],
    films: ["6"],
    id: "62"
  },
  {
    name: "Droid tri-fighter",
    model: "tri-fighter",
    manufacturer: "Colla Designs, Phlac-Arphocc Automata Industries",
    cost_in_credits: "20000",
    length: "5.4",
    max_atmosphering_speed: "1180",
    crew: "1",
    passengers: "0",
    cargo_capacity: "0",
    consumables: "none",
    vehicle_class: "droid starfighter",
    pilots: [],
    films: ["6"],
    id: "67"
  },
  {
    name: "Oevvaor jet catamaran",
    model: "Oevvaor jet catamaran",
    manufacturer: "Appazanna Engineering Works",
    cost_in_credits: "12125",
    length: "15.1",
    max_atmosphering_speed: "420",
    crew: "2",
    passengers: "2",
    cargo_capacity: "50",
    consumables: "3 days",
    vehicle_class: "airspeeder",
    pilots: [],
    films: ["6"],
    id: "69"
  },
  {
    name: "Raddaugh Gnasp fluttercraft",
    model: "Raddaugh Gnasp fluttercraft",
    manufacturer: "Appazanna Engineering Works",
    cost_in_credits: "14750",
    length: "7",
    max_atmosphering_speed: "310",
    crew: "2",
    passengers: "0",
    cargo_capacity: "20",
    consumables: "none",
    vehicle_class: "air speeder",
    pilots: [],
    films: ["6"],
    id: "70"
  },
  {
    name: "Clone turbo tank",
    model: "HAVw A6 Juggernaut",
    manufacturer: "Kuat Drive Yards",
    cost_in_credits: "350000",
    length: "49.4",
    max_atmosphering_speed: "160",
    crew: "20",
    passengers: "300",
    cargo_capacity: "30000",
    consumables: "20 days",
    vehicle_class: "wheeled walker",
    pilots: [],
    films: ["6"],
    id: "71"
  },
  {
    name: "Corporate Alliance tank droid",
    model: "NR-N99 Persuader-class droid enforcer",
    manufacturer: "Techno Union",
    cost_in_credits: "49000",
    length: "10.96",
    max_atmosphering_speed: "100",
    crew: "0",
    passengers: "4",
    cargo_capacity: "none",
    consumables: "none",
    vehicle_class: "droid tank",
    pilots: [],
    films: ["6"],
    id: "72"
  },
  {
    name: "Droid gunship",
    model: "HMP droid gunship",
    manufacturer: "Baktoid Fleet Ordnance, Haor Chall Engineering",
    cost_in_credits: "60000",
    length: "12.3",
    max_atmosphering_speed: "820",
    crew: "0",
    passengers: "0",
    cargo_capacity: "0",
    consumables: "none",
    vehicle_class: "airspeeder",
    pilots: [],
    films: ["6"],
    id: "73"
  },
  {
    name: "AT-RT",
    model: "All Terrain Recon Transport",
    manufacturer: "Kuat Drive Yards",
    cost_in_credits: "40000",
    length: "3.2",
    max_atmosphering_speed: "90",
    crew: "1",
    passengers: "0",
    cargo_capacity: "20",
    consumables: "1 day",
    vehicle_class: "walker",
    pilots: [],
    films: ["6"],
    id: "76"
  },
  {
    name: "AT-TE",
    model: "All Terrain Tactical Enforcer",
    manufacturer: "Rothana Heavy Engineering, Kuat Drive Yards",
    cost_in_credits: "unknown",
    length: "13.2",
    max_atmosphering_speed: "60",
    crew: "6",
    passengers: "36",
    cargo_capacity: "10000",
    consumables: "21 days",
    vehicle_class: "walker",
    pilots: [],
    films: ["5", "6"],
    id: "53"
  },
  {
    name: "SPHA",
    model: "Self-Propelled Heavy Artillery",
    manufacturer: "Rothana Heavy Engineering",
    cost_in_credits: "unknown",
    length: "140",
    max_atmosphering_speed: "35",
    crew: "25",
    passengers: "30",
    cargo_capacity: "500",
    consumables: "7 days",
    vehicle_class: "walker",
    pilots: [],
    films: ["5"],
    id: "54"
  },
  {
    name: "Flitknot speeder",
    model: "Flitknot speeder",
    manufacturer: "Huppla Pasa Tisc Shipwrights Collective",
    cost_in_credits: "8000",
    length: "2",
    max_atmosphering_speed: "634",
    crew: "1",
    passengers: "0",
    cargo_capacity: "unknown",
    consumables: "unknown",
    vehicle_class: "speeder",
    pilots: ["67"],
    films: ["5"],
    id: "55"
  },
  {
    name: "Neimoidian shuttle",
    model: "Sheathipede-class transport shuttle",
    manufacturer: "Haor Chall Engineering",
    cost_in_credits: "unknown",
    length: "20",
    max_atmosphering_speed: "880",
    crew: "2",
    passengers: "6",
    cargo_capacity: "1000",
    consumables: "7 days",
    vehicle_class: "transport",
    pilots: [],
    films: ["5", "6"],
    id: "56"
  },
  {
    name: "Geonosian starfighter",
    model: "Nantex-class territorial defense",
    manufacturer: "Huppla Pasa Tisc Shipwrights Collective",
    cost_in_credits: "unknown",
    length: "9.8",
    max_atmosphering_speed: "20000",
    crew: "1",
    passengers: "0",
    cargo_capacity: "unknown",
    consumables: "unknown",
    vehicle_class: "starfighter",
    pilots: [],
    films: ["5"],
    id: "57"
  }
];
