// flow-typed signature: 5b219ffa9d4bf444dee3299f4440c78b
// flow-typed version: <<STUB>>/jasmine-check_v^1.0.0-rc.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jasmine-check'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jasmine-check' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jasmine-check/jasmine-check' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jasmine-check/jasmine-check.js' {
  declare module.exports: $Exports<'jasmine-check/jasmine-check'>;
}
