const modules = require("./index");

Promise.all(
  Object.keys(modules).filter(data => data !== "__esModule").map(data =>
    describe(`Module ${data} is defined and has id, createdAt and updatedAt`, () => {
      const attributes = Object.keys(modules[data].attributes);
      it("contains attributes", () => expect(attributes).toBeDefined());
      it("contains an id field", () => expect(attributes).toContain("id"));
      it("Should automatically increment the id", () =>
        expect(modules[data].attributes.id.autoIncrement).toBe(true));
      it("Should have ID as a primary key", () =>
        expect(modules[data].attributes.id.primaryKey).toBe(true));
      it("contains a createdAt field", () =>
        expect(attributes).toContain("createdAt"));
      it("Should automate creation timestamp on insert", () =>
        expect(modules[data].attributes.createdAt._autoGenerated).toBe(true));
      it("contains an updatedAt field", () =>
        expect(attributes).toContain("updatedAt"));
      it("Should automate edit timestamp on insert", () =>
        expect(modules[data].attributes.updatedAt._autoGenerated).toBe(true));
    })
  )
);
